version: '3'

services:
  langflow:
    container_name: langflow
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./python/src/backend/langflow/:/home/user/app/langflow/
      - ./.prod_env:/home/user/app/.prod_env
    network_mode: "host"
    ports:
      - "7860:7860"
    command: ["/bin/bash", "-c", "cd /home/user/app/ && python -m langflow run --host 0.0.0.0 --env-file /home/user/app/.prod_env"]
