version: '3'

services:
  langflow:
    user: root
    privileged: true
    # 方式一, 使用已有镜像启动
    # image: langflow:latest
    # 方式二, 使用dockerfile构建镜像
    container_name: langflow
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./python/src/backend/langflow/:/home/user/app/langflow/
      - ./.prod_env:/home/user/app/.prod_env
      - ./python/src/backend/logs/:/home/user/app/logs/
    network_mode: "host"
    ports:
      - "7860:7860"
    command: ["/bin/bash", "-c", "cd /home/user/app/ && python -m langflow run --host 0.0.0.0 --env-file /home/user/app/.prod_env"]
